python neural_b.py data/ essentials/part_a_and_b/multiclass_dataset/tc_1 essentials/part_a_and_b/multiclass_dataset/tc_1/param.txt
python essentials/part_a_and_b/weight_check_demo_l.py essentials/part_a_and_b/multiclass_dataset/tc_1
python essentials/part_a_and_b/weight_check_demo_l_iter.py essentials/part_a_and_b/multiclass_dataset/tc_1

python neural_b.py data/ essentials/part_a_and_b/multiclass_dataset/tc_2 essentials/part_a_and_b/multiclass_dataset/tc_2/param.txt
python essentials/part_a_and_b/weight_check_demo_l.py essentials/part_a_and_b/multiclass_dataset/tc_2
python essentials/part_a_and_b/weight_check_demo_l_iter.py essentials/part_a_and_b/multiclass_dataset/tc_2

python neural_b.py data/ essentials/part_a_and_b/multiclass_dataset/tc_3 essentials/part_a_and_b/multiclass_dataset/tc_3/param.txt
python essentials/part_a_and_b/weight_check_demo_l.py essentials/part_a_and_b/multiclass_dataset/tc_3
python essentials/part_a_and_b/weight_check_demo_l_iter.py essentials/part_a_and_b/multiclass_dataset/tc_3